build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    environment:
        node: 10.15.3
        variables:
            COMPOSER_MEMORY_LIMIT: -1

filter:
    excluded_paths: [tests/*, spec/*]
