imports:
    - { resource: "indexes/bitbag_shop_products.yml" }
    - { resource: "indexes/bitbag_option_taxons.yml" }
    - { resource: "indexes/bitbag_attribute_taxons.yml" }
    - { resource: "indexes/bitbag_shop_facets.yml" }
    - { resource: "state_machine/sylius_order.yaml" }

parameters:
    bitbag_es_host: localhost
    bitbag_es_port: 9200

fos_elastica:
    clients:
        default:
            host: "%bitbag_es_host%"
            port: "%bitbag_es_port%"
