bitbag_sylius_elasticsearch_plugin_shop_list_products:
    path: /{_locale}/products-list/{slug}
    defaults:
        _controller: bitbag_sylius_elasticsearch_plugin.controller.action.shop.taxon_products_search
        template: "@BitBagSyliusElasticsearchPlugin/Shop/Product/index.html.twig"
    requirements:
        slug: .+

bitbag_sylius_elasticsearch_plugin_shop_auto_complete_product_name:
    path: /{_locale}/auto-complete/product
    defaults:
        _controller: bitbag_sylius_elasticsearch_plugin.controller.action.shop.auto_complete_product_name
    requirements:
        slug: .+

bitbag_sylius_elasticsearch_plugin_shop_search:
    path: /{_locale}/search
    defaults:
        _controller: bitbag_sylius_elasticsearch_plugin.controller.action.shop.site_wide_products_search
        template: "@BitBagSyliusElasticsearchPlugin/Shop/search.html.twig"
