imports:
    - { resource: "indexes/bitbag_shop_products.yml" }
    - { resource: "indexes/bitbag_option_taxons.yml" }
    - { resource: "indexes/bitbag_attribute_taxons.yml" }
    - { resource: "indexes/bitbag_shop_facets.yml" }

parameters:
    env(BITBAG_ES_INDEX_PREFIX): ""
    env(BITBAG_ES_HOST): "localhost"
    env(BITBAG_ES_PORT): "9200"
    bitbag_es_index_prefix: "%env(BITBAG_ES_INDEX_PREFIX)%"
    bitbag_es_host: "%env(BITBAG_ES_HOST)%"
    bitbag_es_port: "%env(BITBAG_ES_PORT)%"

    bitbag_es_pagination_available_page_limits: [9, 18, 36]
    bitbag_es_pagination_default_limit: 9
    bitbag_es_fuzziness: AUTO
    bitbag_es_facets_auto_discover: true
    bitbag_es_excluded_facet_attributes: []
    bitbag_es_excluded_facet_options: []

fos_elastica:
    clients:
        default:
            host: "%bitbag_es_host%"
            port: "%bitbag_es_port%"

twig:
    globals:
        bitbag_es_pagination_available_page_limits: "%bitbag_es_pagination_available_page_limits%"

sylius_twig_hooks:
    hooks:
        'sylius_shop.base.header.content':
            search_form:
                template: "@BitBagSyliusElasticsearchPlugin/Shop/Layout/Header/searchForm.html.twig"
                priority: 250
        'sylius_shop.base.header.content.search_form':
            content:
                component: 'bitbag.sylius_elasticsearch_plugin:search_form'
                props:
                    template: "@BitBagSyliusElasticsearchPlugin/Shop/SearchForm/searchForm.html.twig"
                priority: 0

        'bitbag.sylius_elasticsearch_plugin.site_wide_search.index':
            content:
                template: '@SyliusShop/product/index/content.html.twig'
                priority: 0
        'bitbag.sylius_elasticsearch_plugin.site_wide_search.index.content':
            breadcrumbs:
                template: "@BitBagSyliusElasticsearchPlugin/Shop/SiteWideSearch/content/breadcrumbs.html.twig"
                priority: 100
            body:
                template: '@SyliusShop/product/index/content/body.html.twig'
                priority: 0
        'bitbag.sylius_elasticsearch_plugin.site_wide_search.index.content.body':
            sidebar:
                template: '@SyliusShop/product/index/content/body/sidebar.html.twig'
                priority: 100
            main:
                template: '@SyliusShop/product/index/content/body/main.html.twig'
                priority: 0
        'bitbag.sylius_elasticsearch_plugin.site_wide_search.index.content.body.sidebar':
            facets:
                template: '@BitBagSyliusElasticsearchPlugin/Shop/SiteWideSearch/content/body/sidebar/facets.html.twig'
                priority: 0
        'bitbag.sylius_elasticsearch_plugin.site_wide_search.index.content.body.main':
            filters:
                template: '@SyliusShop/product/index/content/body/main/filters.html.twig'
                priority: 200
            products:
                template: '@BitBagSyliusElasticsearchPlugin/Shop/SiteWideSearch/content/body/main/products.html.twig'
                priority: 100
            pagination:
                template: '@BitBagSyliusElasticsearchPlugin/Shop/SiteWideSearch/content/body/main/pagination.html.twig'
                priority: 0
        'bitbag.sylius_elasticsearch_plugin.site_wide_search.index.content.body.main.filters':
            controls:
                template: '@SyliusShop/product/index/content/body/main/filters/controls.html.twig'
                priority: 0
        'bitbag.sylius_elasticsearch_plugin.site_wide_search.index.content.body.main.filters.controls':
            limit:
                template: '@SyliusShop/product/index/content/body/main/filters/controls/limit.html.twig'
                priority: 100
            sorting:
                template: '@BitBagSyliusElasticsearchPlugin/Shop/SiteWideSearch/content/body/main/sorting.html.twig'
                priority: 0
        'bitbag.sylius_elasticsearch_plugin.site_wide_search.index.content.body.main.filters.controls.limit':
            toggle:
                template: '@BitBagSyliusElasticsearchPlugin/Shop/SiteWideSearch/content/body/main/limit/toggle.html.twig'
                priority: 100
            menu:
                template: '@BitBagSyliusElasticsearchPlugin/Shop/SiteWideSearch/content/body/main/limit/menu.html.twig'
                priority: 0
        'bitbag.sylius_elasticsearch_plugin.site_wide_search.index.content.body.main.filters.controls.sorting':
            toggle:
                template: '@SyliusShop/product/index/content/body/main/filters/controls/sorting/toggle.html.twig'
                priority: 100
            menu:
                template: '@SyliusShop/product/index/content/body/main/filters/controls/sorting/menu.html.twig'
                priority: 0
        'bitbag.sylius_elasticsearch_plugin.site_wide_search.index.content.body.main.filters.controls.sorting.menu':
            bestsellers:
                template: '@BitBagSyliusElasticsearchPlugin/Shop/SiteWideSearch/content/body/main/sorting/item.html.twig'
                configuration:
                    title: 'bitbag_sylius_elasticsearch_plugin.ui.bestsellers'
                    order_by: 'sold_units'
                    sort: 'desc'
                priority: 600
            newest:
                template: '@BitBagSyliusElasticsearchPlugin/Shop/SiteWideSearch/content/body/main/sorting/item.html.twig'
                configuration:
                    title: 'bitbag_sylius_elasticsearch_plugin.ui.newest'
                    order_by: 'product_created_at'
                    sort: 'desc'
                priority: 500
            oldest:
                template: '@BitBagSyliusElasticsearchPlugin/Shop/SiteWideSearch/content/body/main/sorting/item.html.twig'
                configuration:
                    title: 'bitbag_sylius_elasticsearch_plugin.ui.oldest'
                    order_by: 'product_created_at'
                    sort: 'asc'
                priority: 400
            most_expensive:
                template: '@BitBagSyliusElasticsearchPlugin/Shop/SiteWideSearch/content/body/main/sorting/item.html.twig'
                configuration:
                    title: 'bitbag_sylius_elasticsearch_plugin.ui.most_expensive'
                    order_by: 'price'
                    sort: 'desc'
                priority: 300
            cheapest:
                template: '@BitBagSyliusElasticsearchPlugin/Shop/SiteWideSearch/content/body/main/sorting/item.html.twig'
                configuration:
                    title: 'bitbag_sylius_elasticsearch_plugin.ui.cheapest'
                    order_by: 'price'
                    sort: 'asc'
                priority: 200

        'bitbag.sylius_elasticsearch_plugin.taxon_products_search.index':
            content:
                template: '@SyliusShop/product/index/content.html.twig'
                priority: 0
        'bitbag.sylius_elasticsearch_plugin.taxon_products_search.index.content':
            breadcrumbs:
                template: "@BitBagSyliusElasticsearchPlugin/Shop/TaxonProductsSearch/content/breadcrumbs.html.twig"
                priority: 100
            body:
                template: '@SyliusShop/product/index/content/body.html.twig'
                priority: 0
        'bitbag.sylius_elasticsearch_plugin.taxon_products_search.index.content.body':
            sidebar:
                template: '@SyliusShop/product/index/content/body/sidebar.html.twig'
                priority: 100
            main:
                template: '@SyliusShop/product/index/content/body/main.html.twig'
                priority: 0
        'bitbag.sylius_elasticsearch_plugin.taxon_products_search.index.content.body.sidebar':
            facets:
                template: '@BitBagSyliusElasticsearchPlugin/Shop/TaxonProductsSearch/content/body/sidebar/facets.html.twig'
                priority: 0
        'bitbag.sylius_elasticsearch_plugin.taxon_products_search.index.content.body.main':
            filters:
                template: '@SyliusShop/product/index/content/body/main/filters.html.twig'
                priority: 200
            search:
                template: '@BitBagSyliusElasticsearchPlugin/Shop/TaxonProductsSearch/content/body/main/search.html.twig'
                priority: 150
            products:
                template: '@BitBagSyliusElasticsearchPlugin/Shop/TaxonProductsSearch/content/body/main/products.html.twig'
                priority: 100
            pagination:
                template: '@BitBagSyliusElasticsearchPlugin/Shop/TaxonProductsSearch/content/body/main/pagination.html.twig'
                priority: 0

        'bitbag.sylius_elasticsearch_plugin.taxon_products_search.index.content.body.main.filters':
            controls:
                template: '@SyliusShop/product/index/content/body/main/filters/controls.html.twig'
                priority: 0
        'bitbag.sylius_elasticsearch_plugin.taxon_products_search.index.content.body.main.filters.controls':
            limit:
                template: '@SyliusShop/product/index/content/body/main/filters/controls/limit.html.twig'
                priority: 100
            sorting:
                template: '@BitBagSyliusElasticsearchPlugin/Shop/TaxonProductsSearch/content/body/main/sorting.html.twig'
                priority: 0
        'bitbag.sylius_elasticsearch_plugin.taxon_products_search.index.content.body.main.filters.controls.limit':
            toggle:
                template: '@BitBagSyliusElasticsearchPlugin/Shop/TaxonProductsSearch/content/body/main/limit/toggle.html.twig'
                priority: 100
            menu:
                template: '@BitBagSyliusElasticsearchPlugin/Shop/TaxonProductsSearch/content/body/main/limit/menu.html.twig'
                priority: 0
        'bitbag.sylius_elasticsearch_plugin.taxon_products_search.index.content.body.main.filters.controls.sorting':
            toggle:
                template: '@SyliusShop/product/index/content/body/main/filters/controls/sorting/toggle.html.twig'
                priority: 100
            menu:
                template: '@SyliusShop/product/index/content/body/main/filters/controls/sorting/menu.html.twig'
                priority: 0
        'bitbag.sylius_elasticsearch_plugin.taxon_products_search.index.content.body.main.filters.controls.sorting.menu':
            bestsellers:
                template: '@BitBagSyliusElasticsearchPlugin/Shop/TaxonProductsSearch/content/body/main/sorting/item.html.twig'
                configuration:
                    title: 'bitbag_sylius_elasticsearch_plugin.ui.bestsellers'
                    order_by: 'sold_units'
                    sort: 'desc'
                priority: 600
            newest:
                template: '@BitBagSyliusElasticsearchPlugin/Shop/TaxonProductsSearch/content/body/main/sorting/item.html.twig'
                configuration:
                    title: 'bitbag_sylius_elasticsearch_plugin.ui.newest'
                    order_by: 'product_created_at'
                    sort: 'desc'
                priority: 500
            oldest:
                template: '@BitBagSyliusElasticsearchPlugin/Shop/TaxonProductsSearch/content/body/main/sorting/item.html.twig'
                configuration:
                    title: 'bitbag_sylius_elasticsearch_plugin.ui.oldest'
                    order_by: 'product_created_at'
                    sort: 'asc'
                priority: 400
            most_expensive:
                template: '@BitBagSyliusElasticsearchPlugin/Shop/TaxonProductsSearch/content/body/main/sorting/item.html.twig'
                configuration:
                    title: 'bitbag_sylius_elasticsearch_plugin.ui.most_expensive'
                    order_by: 'price'
                    sort: 'desc'
                priority: 300
            cheapest:
                template: '@BitBagSyliusElasticsearchPlugin/Shop/TaxonProductsSearch/content/body/main/sorting/item.html.twig'
                configuration:
                    title: 'bitbag_sylius_elasticsearch_plugin.ui.cheapest'
                    order_by: 'price'
                    sort: 'asc'
                priority: 200
